# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.21)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget cryptopp-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target cryptopp-static
add_library(cryptopp-static STATIC IMPORTED)

set_target_properties(cryptopp-static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "CRYPTOPP_DATA_DIR=D:/source/repos/DFW2/UMC/CryptoPP/TestData;_WIN32_WINNT=0x0A00"
  INTERFACE_INCLUDE_DIRECTORIES "D:/source/repos/DFW2/UMC/CryptoPP"
)

# Import target "cryptopp-static" for configuration "Debug"
set_property(TARGET cryptopp-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(cryptopp-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "ASM_MASM;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "kernel32"
  IMPORTED_LOCATION_DEBUG "D:/source/repos/DFW2/UMC/CryptoPP/Debug/cryptopp-static.lib"
  )

# Import target "cryptopp-static" for configuration "Release"
set_property(TARGET cryptopp-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cryptopp-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "ASM_MASM;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "kernel32"
  IMPORTED_LOCATION_RELEASE "D:/source/repos/DFW2/UMC/CryptoPP/Release/cryptopp-static.lib"
  )

# Import target "cryptopp-static" for configuration "MinSizeRel"
set_property(TARGET cryptopp-static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(cryptopp-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "ASM_MASM;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "kernel32"
  IMPORTED_LOCATION_MINSIZEREL "D:/source/repos/DFW2/UMC/CryptoPP/MinSizeRel/cryptopp-static.lib"
  )

# Import target "cryptopp-static" for configuration "RelWithDebInfo"
set_property(TARGET cryptopp-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(cryptopp-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "ASM_MASM;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "kernel32"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/source/repos/DFW2/UMC/CryptoPP/RelWithDebInfo/cryptopp-static.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
