// Compiler.idl : IDL source for Compiler
//

// This file will be processed by the MIDL tool to
// produce the type library (Compiler.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(D467511C-F649-495B-9568-F3E17FA9BC73),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IAutomaticCompiler : IDispatch
{
	[id(0), helpstring("Add Starter")] HRESULT AddStarter([in]LONG Type,
														  [in]LONG Id, 
														  [in]BSTR Name, 
														  [in]BSTR Expression, 
														  [in]LONG LinkType,
														  [in]BSTR ObjectClass,
														  [in]BSTR ObjectKey,
														  [in]BSTR ObjectProp);

	[id(1), helpstring("Add Logic")] HRESULT AddLogic([in]LONG Type,
													  [in]LONG Id, 
													  [in]BSTR Name,
													  [in]BSTR Expression,
													  [in]BSTR Actions,
													  [in]BSTR DelayExpression,
													  [in]LONG OutputMode);

	[id(2), helpstring("Add Action")] HRESULT AddAction([in]LONG Type,
														[in]LONG Id,
														[in]BSTR Name,
														[in]BSTR Expression,
														[in]LONG LinkType,
														[in]BSTR ObjectClass,
														[in]BSTR ObjectKey,
														[in]BSTR ObjectProp,
														[in]LONG ActionGroup,
														[in]LONG OutputMode,
														[in]LONG RunsCount);

	[id(3), helpstring("Compile")] HRESULT Compile();
	[propget, id(4), helpstring("Get Log")] HRESULT Log([out, retval]VARIANT* LogArray);

};
[
	uuid(537DB855-A1FF-4069-92F7-CF9CFB0F3E3D),
	version(1.0),
]
library CompilerLib
{
	importlib("stdole2.tlb");
	[
		uuid(98056FA0-6611-4DF0-BF7B-6ED6A78A358A)		
	]
	coclass AutomaticCompiler
	{
		[default] interface IAutomaticCompiler;
	};
};

